### ISSUE TITLE
README claims FITS 0.6.2 is required???

### ISSUE THREAD

**Issue by mark-dce** [projecthydra/hydra-derivatives#100]
It looks like hydra-derivatives now expects FITS 0.8.x output or something similar.  Can someone confirm which versions of FITS are compatible with the current release (3.0.1) of hydra-derivatives and update the README?  

The current README says version 0.6.2 is required here: https://github.com/projecthydra/hydra-derivatives#dependencies

**Comment by mjgiarlo** [comment]
Fixed. Thanks!
