### ISSUE TITLE
Flattening should not be global

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/hydra-derivatives#128]
We don't really want any of [this flattening business](https://github.com/projecthydra/hydra-derivatives/commit/9df9746fb91c00b5cce8305f6a990a67fbd34d43). Best way to make it optional? @awead

**Comment by hackmastera** [comment]
I'd prefer to pass an option to `Hydra::Derivatives::ImageDerivatives.create` since I'm already doing derivatives creation on a mime-type-switch basis.

**Comment by awead** [comment]
@hackmastera you can do `xfrm.flatten if flatten?`

``` ruby

private
  
  def flatten?
    directives.fetch(:flatten, "true")
  end
```

So it will flatten by default, but you can disable it if you need to.

**Comment by hackmastera** [comment]
Okay thanks, @awead. For now I was able to use the `layer` parameter to solve my problem by setting it to layer 0.
