### ISSUE TITLE
Specify custom processor

### ISSUE THREAD

**Issue by awead** [projecthydra/hydra-derivatives#55]
If I want to create my own processor class, I have to create an instance of `Hydra::Derivatives::MyProcessor`. It would easier to create:
``` ruby
class MyProcessor < Hydra::Derivatives::Image
end
```
and pass that class in the `makes_derivatives` block. From what I can tell, I can't do that.

**Comment by jcoyne** [comment]
@awead is this closed?

**Comment by jcoyne** [comment]
we've gotten rid of makes_derivatives and instead just run the job: https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/models/concerns/curation_concerns/generic_file/derivatives.rb#L14-L37
