### ISSUE TITLE
output_file_service should pass a file that responds to .mime_type

### ISSUE THREAD

**Issue by tampakis** [projecthydra/hydra-derivatives#67]
The output file service is configured to pass around mime_type as an option and use that when attaching files. Rather than passing around the mime_type option, the file object should respond to .mime_type. Also the file sent to the output file service should respond to .read. This is blocking https://github.com/projecthydra-labs/hydra-works/pull/183

Anything that calls .output_file_service (as well as uses it such as the [PersistBasicContainedOutputFile service](https://github.com/projecthydra/hydra-derivatives/blob/7a8377c12ba1697f825cef9f5b2cd3ec7b844228/lib/hydra/derivatives/services/persist_basic_contained_output_file_service.rb#L19)) should be modified to remove the mime_type option and to make sure the file passed around responds to .mime_type.
These are mainly found in the derivative processors:
 - [document processor](https://github.com/projecthydra/hydra-derivatives/blob/7a8377c12ba1697f825cef9f5b2cd3ec7b844228/lib/hydra/derivatives/document.rb#L27) 
 - [jpeg2k_image processor](https://github.com/projecthydra/hydra-derivatives/blob/7a8377c12ba1697f825cef9f5b2cd3ec7b844228/lib/hydra/derivatives/jpeg2k_image.rb#L39)
 - [image processor](https://github.com/projecthydra/hydra-derivatives/blob/faba8703e5b77807bec1100c04f72f35018cf115/lib/hydra/derivatives/image.rb#L61)
 - [shell_based_processor](https://github.com/projecthydra/hydra-derivatives/blob/7a8377c12ba1697f825cef9f5b2cd3ec7b844228/lib/hydra/derivatives/shell_based_processor.rb#L39)

**Comment by grosscol** [comment]
I agree with this assessment. The what .output_file_service resolves to is configurable and the default is PersistBasicContainedOutputFileService.  I'm currently working my way through the derivatives logic to make sure that the file objects respond to .mime_type.  Wrapping them in a class with that attribute should only break downstream projects that check the class of returned files... which is probably a code smell anyway.

**Comment by grosscol** [comment]
Closed by #68
