### ISSUE TITLE
original_name is never set in PersistBasicContainedOutputFileService

### ISSUE THREAD

**Issue by tampakis** [projecthydra/hydra-derivatives#78]
All of the processors wrap files/IO streams in a [IoDecorator](https://github.com/projecthydra/hydra-derivatives/blob/master/lib/hydra/derivatives/io_decorator.rb) class, which responds to `.original_name`. It isn't set in the processors, so currently it is up to the output_file_service to determine its value. The [PersistBasicContainedOutputFileService](https://github.com/projecthydra/hydra-derivatives/blob/master/lib/hydra/derivatives/services/persist_basic_contained_output_file_service.rb#L18) uses the [determine_original_name](https://github.com/projecthydra/hydra-derivatives/blob/master/lib/hydra/derivatives/services/persist_output_file_service.rb#L14) method to set it with a value. However, since all of the IoDecorator objects respond to `.original_name` and that value is nil, the function returns nil.

I'm not really sure how `original_name` is used outside of Derivatives, but maybe we should have it set in the processors to ensure it returns a non-nil value.

**Comment by grosscol** [comment]
I put original_name in there as it was an active fedora attribute that would get assigned if present, and was a stand in for the file path on disk argument that had been used downstream in Hydra::Works for file upload.

The original_name defaults in the output file service, as it does get used downstream in curation concerns for file characterization.  I assumed it was being used or would be used in subsequent iterations, but only need to have a sane default at the point of passing things off to the persistence layer.
