### ISSUE TITLE
switch from Popen3 to posix-spawn

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/hydra-derivatives#81]
See hydra-tech message from 9/4/2015:

https://groups.google.com/forum/#!searchin/hydra-tech/derivatives$20deadlock/hydra-tech/_L2ysL1A0M8/2agSkvWVFAAJ

I'm having the same problem. It seems like their fix could be pushed upstream.

https://github.com/NLIreland/hydra-derivatives/commit/28ce9fdd3754c06f84136ce44502506f449dc4b6

Happy to do this and submit a PR unless there's a reason not to.

**Comment by eocarragain** [comment]
Thanks! As an update, since Lutz posted that message we've processed derivatives for over 500K objects without any errors. Before switching to posix-spawn, it was a fairly consistent issue (about 1%-2% of derivatives failing with "No live threads. Deadlock?").

This stackoverflow answer put us onto posix-spawn as a solution: http://stackoverflow.com/a/33215181

**Comment by terrellt** [comment]
+1. We had to do this for our Curation Concerns app.

**Comment by jcoyne** [comment]
I think this is due to a bug in hydra-derivatives here:
https://github.com/projecthydra/hydra-derivatives/blob/master/lib/hydra/derivatives/shell_based_processor.rb#L70-L75

One of the pipes is filling (we are not reading until eof is encountered)
and thus the thread is prevented joining. It should use IO.select like
this: https://gist.github.com/chrisn/7450808 to ensure all streams are at
eof.

-Justin

**Comment by eocarragain** [comment]
@jcoyne would this account for errors caused by MiniMagick (i.e. the Image processor)? I didn't think the image processor used the shell_based_processor (we configured MiniMagick to use posix_spawn separately).

**Comment by jcoyne** [comment]
I can't explain why mini_magick is having deadlocks, I only just started seeing hangs with hydra-derivatives (not deadlocks) and I suspect this is the reason.

**Comment by grosscol** [comment]
Was this fixed by using IO.select?

**Comment by hackmastera** [comment]
@grosscol I'm not sure how we can figure that out; I'm not convinced @jcoyne was ever reporting the same error that I and others have observed -- he describes hangs, not deadlocks. Although the error you see in resque isn't particularly conclusive, reading "No live threads left. Deadlock?" Maybe his fix does address both problems.

I don't really know how to reproduce this error, so I'm somewhat hesitant to move forward. Additionally, I don't currently use any of the file types that use the shell_based_processor (ffmpeg, document, and jpeg2k) so I wouldn't really follow this code path on my machine.

Reading the original listserv post again, it sounds like they replaced the hydra-derivatives functionality more out of a desire for a consistency (all posix-spawn, no popen3) or as a precaution than because of an observed problem -- the stack trace given there looks just like mine, which does not go through shell_based_processor.

I was planning to change minimagic configuration to use posix-spawn, but if @jcoyne thinks the root of the maybe-deadlock error was fixed by using IO.select maybe i'll just wait it out.

Either way, unless @eocarragain or @terrellt have some additional insight to add, it doesn't seem like there's really enough evidence to make this code change and I would support closing this issue.

**Comment by eocarragain** [comment]
I'm not sure either; we'd need to carry out some testing across a largish number of objects to see if the "No live threads left. Deadlock?" still occurs. 

In our case the "No live threads left. Deadlock?" error was caused both by generating jpeg2k (shell_based_processor) and jpeg/png thumbnails (Image processor/mini_magick). We switched the mini_magick configuration first which reduced the number of errors, but we still got it for the jpeg2k. We then switched the shell_based_processor to also use posix-spawn which removed the issue entirely. 

The IO.select commit may have fixed the issue for shell_based_processor, but I can't see how it would have fixed it for mini_magick/image processor. Having said that, switching mini_magick to use posix-spawn can be configured outside of hydra-derivatives anyway, so perhaps close the ticket for now & reopen if more people run into the issue in the future.

**Comment by hackmastera** [comment]
@eocarragain thanks you're right, there's no way it would fix the image processor issue, since the IO.select commit only affected the shell_based_process.

Thanks also for the additional info about your errors.

I will close for now and let someone else take this up if they have the material types in question and are observing the problem personally!
